version: '3.7'

services:
  db:
    image: informaticsmatters/rdkit-cartridge-debian:Release_2019_09_2
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./data/database/:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
  genui-main:
    image: ${GENUI_DOCKER_IMAGE_REPO}/genui-main:${GENUI_DOCKER_IMAGE_TAG}
    container_name: genui
    build:
      context: .
      dockerfile: Dockerfile-main
      args:
        GENUI_DOCKER_IMAGE_TAG: ${GENUI_DOCKER_IMAGE_TAG}
        GENUI_DOCKER_IMAGE_REPO: ${GENUI_DOCKER_IMAGE_REPO}
    environment:
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - DJANGO_SETTINGS_MODULE
      - GENUI_BACKEND_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PASSWORD
      - REACT_APP_GENUI_BACKEND_ROOT_URL=${GENUI_BACKEND_PROTOCOL}://${GENUI_BACKEND_HOST}:${GENUI_BACKEND_PORT}/
      - REACT_APP_GENUI_DEPLOY_VERSION=${GENUI_DOCKER_IMAGE_TAG}
      - GENUI_FRONTEND_APP_PATH
      - GENUI_BUILD_FRONTEND=${GENUI_BUILD_FRONTEND:-1}
      - PUBLIC_URL=${GENUI_FRONTEND_APP_PATH}
      - GENUI_USER
      - GENUI_USER_GROUP
    entrypoint: /genui/entrypoint-main.sh
    volumes:
      - ${GENUI_DATA_MOUNT}/media:/genui/data/files/media/
      - ${GENUI_DATA_MOUNT}/home:/home/${GENUI_USER}
      - static:/genui/data/files/static/
      - frontend:/genui/src/genui-gui/build/
      - ./config/nginx/certs/:/etc/certs
      - ${DOCKER_USER_CONFIG_MOUNT}/group:/etc/group:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/passwd:/etc/passwd:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/shadow:/etc/shadow:ro
    expose:
      - ${GENUI_BACKEND_PORT}
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    environment:
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - GENUI_FRONTEND_APP_PATH
      - NGINX_CONF_TEMPLATE=${NGINX_CONF_TEMPLATE:-nginx.conf.template}
    command: /bin/bash -c "envsubst '$$GENUI_BACKEND_PROTOCOL $$GENUI_BACKEND_HOST $$GENUI_BACKEND_PORT $$GENUI_FRONTEND_APP_PATH' < /etc/nginx/conf.d/$$NGINX_CONF_TEMPLATE > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "${GENUI_BACKEND_PORT}:${GENUI_BACKEND_PORT}"
    volumes:
      - ${GENUI_DATA_MOUNT}/media:/usr/share/nginx/html/downloads:ro
      - static:/usr/share/nginx/html/static:ro
      - frontend:/usr/share/nginx/html/app:ro
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - genui-main

volumes:
  static:
  frontend:

# DOCKER_NET_MTU=1442 must be set so that the app works on the openstack cloud
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: ${DOCKER_NET_MTU}
