FROM continuumio/miniconda:latest

# arguments
ARG ROOT_DIR=/genui
ARG BACKEND_DIR=./src/genui
ARG FRONTEND_DIR=./src/genui-gui
ARG DATA_DIR=./data

# environment variables
ENV GENUI_ROOT_DIR=${ROOT_DIR}
ENV GENUI_BACKEND_DIR=${ROOT_DIR}/${BACKEND_DIR}
ENV GENUI_FRONTEND_DIR=${ROOT_DIR}/${FRONTEND_DIR}
ENV GENUI_DATA_DIR=${ROOT_DIR}/${DATA_DIR}
ENV PYTHONUNBUFFERED 1
ENV DOCKER_CONTAINER 1

# authbind: to allow the app process to bind port 443 if run as nonroot
RUN apt-get install -y --no-install-recommends authbind
# wait-for-it: for the worker to wait until the backend is online
RUN apt-get install -y --no-install-recommends wait-for-it

# initialize the backend conda environment
COPY ${BACKEND_DIR}/environment.yml ${GENUI_BACKEND_DIR}/environment.yml
RUN conda install python=3.7 && conda env update -n base --file ${GENUI_BACKEND_DIR}/environment.yml && conda clean --all -y

# install the backend pip packages
COPY ${BACKEND_DIR}/requirements.txt ${GENUI_BACKEND_DIR}/requirements.txt
RUN pip install --no-cache-dir -r ${GENUI_BACKEND_DIR}/requirements.txt

# run updates
#RUN apt-get update && apt-get upgrade -y --no-install-recommends