version: '3.7'

services:
  celery-worker:
    image: sichom/genui:${DOCKER_IMAGE_TAG} # FIXME: the actual worker should have its own image with gpu related libs and stuff
    user: ${GENUI_USER_ID}:${GENUI_USER_GROUP_ID}
    network_mode: "host"
    environment:
      - DJANGO_SETTINGS_MODULE
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - GENUI_BACKEND_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PASSWORD
      - GENUI_USER
      - GENUI_USER_GROUP
      - GENUI_CELERY_NAME=base
    command: wait-for-it ${GENUI_BACKEND_HOST}:${GENUI_BACKEND_PORT} -t 3600 -- celery worker -c ${GENUI_CELERY_CONCURRENCY} -Q ${GENUI_CELERY_QUEUES} -E -A genui --loglevel=info --hostname ${GENUI_CELERY_NAME}@%h
    volumes:
      - ${GENUI_DATA_MOUNT}/media:/code/genui/files/media/
      - ${GENUI_DATA_MOUNT}/home:/home/${GENUI_USER}
      - ${DOCKER_USER_CONFIG_MOUNT}/group:/etc/group:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/passwd:/etc/passwd:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/shadow:/etc/shadow:ro

# DOCKER_NET_MTU=1442 must be set so that the app works on the openstack cloud
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_NET_MTU}