version: '3.7'

services:
    celery-gpu:
        restart: "always"
        container_name: genui-${GENUI_CELERY_NAME:-celery}-gpu_${NVIDIA_VISIBLE_DEVICES:-0}
        image: ${GENUI_DOCKER_IMAGE_PREFIX:-sichom}/genui-gpuworker:${GENUI_DOCKER_IMAGE_TAG:-latest}
        build:
          args:
            GENUI_DOCKER_IMAGE_TAG: ${GENUI_DOCKER_IMAGE_TAG:-latest}
            GENUI_DOCKER_IMAGE_PREFIX: ${GENUI_DOCKER_IMAGE_PREFIX:-sichom}
            NVIDIA_CUDA_RUNFILE: ${NVIDIA_CUDA_RUNFILE:-./config/nvidia/cuda.run}
          context: .
          dockerfile: Dockerfile-gpuworker
        user: ${GENUI_USER_ID:-0}:${GENUI_USER_GROUP_ID:-0}
        environment:
          - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-0}
          - GENUI_BACKEND_PROTOCOL=${GENUI_PROTOCOL}
          - GENUI_BACKEND_HOST=${GENUI_HOST}
          - GENUI_BACKEND_PORT=${GENUI_PORT}
          - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-genui.settings.prod}
          - GENUI_BACKEND_SECRET
          - POSTGRES_DB=${POSTGRES_DB:-genui}
          - POSTGRES_USER=${POSTGRES_USER:-genui}
          - POSTGRES_PASSWORD
          - POSTGRES_HOST=${POSTGRES_HOST:-db}
          - REDIS_HOST=${REDIS_HOST:-redis}
          - REDIS_PASSWORD
          - GENUI_USER=${GENUI_USER:-root}
          - GENUI_USER_GROUP=${GENUI_USER_GROUP:-root}
          - GENUI_CELERY_NAME=${GENUI_CELERY_NAME:-celery}-gpu_${NVIDIA_VISIBLE_DEVICES:-0}
          - GENUI_CELERY_QUEUES=gpu
          - GENUI_CELERY_CONCURRENCY=${GENUI_CELERY_CONCURRENCY:-1}
        command:  wait-for-it ${GENUI_MAIN_NODE_HOST:-genui}:${GENUI_PORT} -t 3600 -- celery worker -O fair --prefetch-multiplier 1 -c ${GENUI_CELERY_CONCURRENCY:-1} -Q ${GENUI_CELERY_QUEUES:-gpu} -E -A genui --loglevel=info --hostname ${GENUI_CELERY_NAME:-celery}-gpu_${NVIDIA_VISIBLE_DEVICES:-0}@%h
        volumes:
          - ${GENUI_DATA_MOUNT:-./genuidata}/media:/genui/data/files/media/
          - ${GENUI_DATA_MOUNT:-./genuidata}/home:/home/${GENUI_USER:-root}
          - ${DOCKER_USER_CONFIG_MOUNT:-/etc}/group:/etc/group:ro
          - ${DOCKER_USER_CONFIG_MOUNT:-/etc}/passwd:/etc/passwd:ro
          - ${DOCKER_USER_CONFIG_MOUNT:-/etc}/shadow:/etc/shadow:ro
#        networks:
#          - genui_back
#networks:
#  genui_back:
#    name: genui_back
#    driver: bridge
#    driver_opts:
#      com.docker.network.driver.mtu: ${DOCKER_NET_MTU:-1500}