ARG DOCKER_IMAGE_TAG=latest
ARG DOCKER_IMAGE_REPO=sichom
FROM ${DOCKER_IMAGE_REPO}/genui-base:${DOCKER_IMAGE_TAG}

# setup dependencies
# wait-for-it: for the worker to wait until the backend is online
RUN apt-get update && apt-get install -y --no-install-recommends wait-for-it

WORKDIR ${GENUI_BACKEND_DIR}/src/