ARG GENUI_DOCKER_IMAGE_TAG=latest
ARG GENUI_DOCKER_IMAGE_PREFIX=sichom
FROM ${GENUI_DOCKER_IMAGE_PREFIX}/genui-base:${GENUI_DOCKER_IMAGE_TAG}

# setup dependencies
# wait-for-it: for the worker to wait until the backend is online
RUN apt-get install -y --no-install-recommends wait-for-it

WORKDIR ${GENUI_BACKEND_DIR}/src/